### ISSUE TITLE
pod5:Empty queue or timeout

### ISSUE THREAD

**Issue by HITzhongyu** [nanoporetech/pod5-file-format#50] opened 2023-06-26 04:04 UTC
Hi，
     When using the command "pod5 convert fast5," I consistently encounter an error that causes the program to stop running. However, upon inspecting my data, I can confirm that the data exists and is actually stored. How can I resolve this issue?

`pod5 convert fast5 ./fast5/*.fast5 --output pod5/`

![image](https://github.com/nanoporetech/pod5-file-format/assets/104176070/04842e96-bfa0-4903-a15a-c617c232c1f5)

**Comment by HalfPhoton** [comment] 2023-06-26 08:28
Hi @HITzhongyu ,

Could you set the `POD5_DEBUG=1` environment variable and run the same command again? The converter will now generate a number of log files which show the state of the Queue at runtime. I can use these to help resolve this issue. 

```
POD5_DEBUG=1 pod5 convert fast5 ./fast5/*.fast5 --output debug_pod5/
```

Kind regards,
Rich

**Comment by HITzhongyu** [comment] 2023-06-27 12:23
Hi @HalfPhoton 

I changed to a new set of test data and reran the command. This time, I encountered an error right from the beginning, as follows:
![image](https://github.com/nanoporetech/pod5-file-format/assets/104176070/61038a85-fd23-467c-b52e-2a9645bec961)
![image](https://github.com/nanoporetech/pod5-file-format/assets/104176070/75c15b76-1447-4bf6-abb9-20419f90a4aa)

However, the program can still run normally. But it gets stuck at 99%  and throws the following error:
![image](https://github.com/nanoporetech/pod5-file-format/assets/104176070/4f191ece-445a-41d2-8245-474d792c791e)

and I try to run `POD5_DEBUG=1 pod5 convert fast5 ./test/*.fast5 --output debug_pod5/`,  the errors are as following:
![image](https://github.com/nanoporetech/pod5-file-format/assets/104176070/cd80fbcf-5837-468b-8915-1d2d09d10534)

**Comment by HalfPhoton** [comment] 2023-06-27 12:46
@HITzhongyu 

The first report shows you using`-t/--threads 40` which is giving a different error to the second report. You might be requesting too many resources which is why the tool is failing to create a new process or thread resulting in `resource temporarily unavailable`. I would suggest reducing the value given to `--threads` 

For the second report which is related to the original issue raised; there should be `.log` files created now that `POD5_DEBUG=1` is set . Can you share those with me please? 

It looks like the Queue that contains the conversion tasks is becoming `empty` somehow or timing out after 600 seconds for a single conversion task (which should be plenty of time for a small chunk of).
The log files will help me track down why this happens. Either the process is getting stuck or the queue logic is failing in your example.

Kind regards,
Rich

**Comment by HITzhongyu** [comment] 2023-06-28 00:53
@HalfPhoton
Here are all the log files, thanks !

[2023-06-27--20-01-54-p-11518-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888372/2023-06-27--20-01-54-p-11518-pod5.log)
[2023-06-27--20-01-54-p-11519-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888373/2023-06-27--20-01-54-p-11519-pod5.log)
[2023-06-27--20-01-54-p-11520-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888375/2023-06-27--20-01-54-p-11520-pod5.log)
[2023-06-27--20-01-54-p-11511-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888367/2023-06-27--20-01-54-p-11511-pod5.log)
[2023-06-27--20-01-54-p-11512-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888368/2023-06-27--20-01-54-p-11512-pod5.log)
[2023-06-27--20-01-54-p-11513-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888369/2023-06-27--20-01-54-p-11513-pod5.log)
[2023-06-27--20-01-54-p-11514-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888370/2023-06-27--20-01-54-p-11514-pod5.log)
[2023-06-27--20-01-54-p-11517-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888371/2023-06-27--20-01-54-p-11517-pod5.log)
[2023-06-27--20-01-52-main-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/11888366/2023-06-27--20-01-52-main-pod5.log)


Kind regards,
Zhongyu

**Comment by HalfPhoton** [comment] 2023-06-28 09:17
Hi @HITzhongyu 

Thank you very much for the logs. They've been very helpful.

From the `main-pod5.log` we can see that one of the worker processes has been killed from a `segmentation fault` 
```
2023-06-27 20:21:44,357 DEBUG 66:'terminate_processes': ... SpawnProcess-11, stopped[SIGSEGV] daemon ...
```

and in the worker `11513-pod5.log` we see that the log ends abruptly here:
```
--- Finishing previous file FAQ32498_pass_09083b73_65.fast5
2023-06-27 20:11:05,414 DEBUG 53:'convert_fast5_file':Done:37.193s
2023-06-27 20:11:05,425 DEBUG 53:'convert_fast5_file':Returned:4000
2023-06-27 20:11:05,427 INFO Enqueueing file end: FAQ32498_pass_09083b73_65.fast5 reads: 4000
2023-06-27 20:11:05,428 DEBUG c7:'enqueue_data'

--- Getting next file FAQ32498_pass_09083b73_71.fast5
2023-06-27 20:11:05,430 DEBUG 56:'get_input':(<pod5.tools.pod5_convert_from_fast5.QueueManager object at 0x7f8b6c3b5b10>,), {}
2023-06-27 20:11:05,430 DEBUG 56:'get_input':Done:0.000s
2023-06-27 20:11:05,430 DEBUG 56:'get_input':Returned:test/FAQ32498_pass_09083b73_71.fast5

--- Testing is_multi_read_fast5 on FAQ32498_pass_09083b73_71.fast5
2023-06-27 20:11:05,431 DEBUG 72:'is_multi_read_fast5':(PosixPath('test/FAQ32498_pass_09083b73_71.fast5'),), {}

--- Segfault
```

We'd expect to see 
```
2023-06-27 20:10:26,479 DEBUG fd:'is_multi_read_fast5':(PosixPath('test/FAQ32498_pass_09083b73_65.fast5'),), {}
2023-06-27 20:10:28,220 DEBUG fd:'is_multi_read_fast5':Done:1.741s
2023-06-27 20:10:28,220 DEBUG fd:'is_multi_read_fast5':Returned:True
``` 

Can you please try and check that this file `test/FAQ32498_pass_09083b73_71.fast5` is not corrupt in some way?

Kind regards,
Rich

**Comment by HITzhongyu** [comment] 2023-06-28 10:06
Hi @HalfPhoton 
I try to open `test/FAQ32498_pass_09083b73_71.fast5`,but HDFView can't open it 
I can upload the file to you,and you can test it

**Comment by HalfPhoton** [comment] 2023-06-28 10:23
@HITzhongyu , 
Can you open it with python?

Using the same environment where pod5 is installed these module imports should exists:
``` python
# Get the a path to the file
from pathlib import Path
path = Path("test/FAQ32498_pass_09083b73_71.fast5")
assert path.exists()

# Can we open the file with h5py? If it fails here then the HDF5 file is corrupted somehow
import h5py
h5 = h5py.File(path)

# Is the file empty? If it fails here there's nothing to do anyway and the file should be deleted 
assert len(h5) > 0

# Can pod5 check the file? If it fails here then there might be something we can do
from pod5.tools.pod5_convert_from_fast5 import is_multi_read_fast5
is_multi_read_fast5(pp)
```

**Comment by HITzhongyu** [comment] 2023-06-28 10:29
@HalfPhoton 
 it report an error :    Segmentation fault (core dumped)
![image](https://github.com/nanoporetech/pod5-file-format/assets/104176070/3aa709c7-c6f1-40cb-98be-db7c73f544b8)

**Comment by HalfPhoton** [comment] 2023-06-28 10:41
Ok,

Please try this:

```python
print("start")
with h5py.File(path) as _h5:
  print("open")           
  print(_h5)

  _h5.attrs
  print("can access_h5.attrs")
  print(_h5.attrs)

  # The "file_type" attribute might be present on supported multi-read fast5 files.
  if _h5.attrs.get("file_type") == "multi-read":
    return True
  print( "is not multi-read file type")

  if len(_h5) == 0:
    return True
  print( "is not len 0")

  # if there are "read_x" keys, this is a multi-read file
  if any(key for key in _h5 if key.startswith("read_")):
   print("found a read")
    return True

  print("closing handle")
print("everything is fine?!")
```

**Comment by HITzhongyu** [comment] 2023-06-28 10:48
I modify your code，because it cause some error

```
print("start")
with h5py.File(path) as _h5:
    print("open")           
    print(_h5)

    _h5.attrs
    print("can access_h5.attrs")
    print(_h5.attrs)

    # The "file_type" attribute might be present on supported multi-read fast5 files.
    if _h5.attrs.get("file_type") == "multi-read":
        print("True")
        # return True
    print( "is not multi-read file type")

    if len(_h5) == 0:
        print("True")
        # return True
    print( "is not len 0")

    # if there are "read_x" keys, this is a multi-read file
    if any(key for key in _h5 if key.startswith("read_")):
        print("found a read")
        # return True

    print("closing handle")
print("everything is fine?!")
```

It reports an error:
```
start
open
<HDF5 file "FAQ32498_pass_09083b73_71.fast5" (mode r)>
can access_h5.attrs
<Attributes of HDF5 object at 139974581599904>
is not multi-read file type
is not len 0
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    if any(key for key in _h5 if key.startswith("read_")):
  File "test.py", line 40, in <genexpr>
    if any(key for key in _h5 if key.startswith("read_")):
  File "/home/user/ydliu/miniconda3/envs/remora/lib/python3.8/site-packages/h5py/_hl/group.py", line 499, in __iter__
    for x in self.id.__iter__():
  File "h5py/h5g.pyx", line 128, in h5py.h5g.GroupIter.__next__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 316, in h5py.h5l.LinkProxy.iterate
RuntimeError: Link iteration failed (incorrect metadata checksum after all read attempts)
```

**Comment by HalfPhoton** [comment] 2023-06-28 11:10
Hi @HITzhongyu ,

It does appear that your fast5 file is corrupt. This is the same issue as seen here: [megalodon#279](https://github.com/nanoporetech/megalodon/issues/279)

I'm not sure what we can do other than to recommend that you check your files, and drop those that are corrupt before continuing with `pod5 subset`

Apologies we don't have better solution.

Kind regards,
Rich

**Comment by HITzhongyu** [comment] 2023-06-28 11:17
Hi @HalfPhoton 

Thank you very much for your patient explanation. 

Regarding this issue, can you perform a filtering step before converting with pod5, skipping any damaged Fast5 files that are recognized as single Fast5, without affecting the subsequent program execution? If there are only a few such damaged data points, it should not impact the results of large-scale methylation detection.

or if it's convenient for you, could you please let me know which part of the code needs to be modified? I can make the changes on my end.

Kind regards,
Rich

**Comment by HalfPhoton** [comment] 2023-06-28 11:26
@HITzhongyu 

`pod5 subset` will try to ignore bad fast5 unless `--strict` is set. We removed the up-front fast5 checking because it was so slow.

In your case, the files are causing a prompt segfault which kills the worker process immediately instead of allowing it to handle the error gracefully. This is an issue with `h5py`.

There potential changes we can make to how we handle dead workers which we might investigate.

As for how Guppy can handle this file when pod5 cannot; I'm not sure, but Guppy is not using python / `h5py` which is where I believe the issue is caused.

Kind regards,
Rich

**Comment by HITzhongyu** [comment] 2023-06-28 11:30
@HalfPhoton 

Thank you very much for your patient explanation!

Kind regards,
Zhongyu

**Comment by HITzhongyu** [comment] 2023-06-28 11:42
Hi @HalfPhoton 
I find `pod5 subset`  to check pod5 not fast5
```(py37) [ydliu@ln01 HG002]$ pod5 subset -h
usage: pod5 subset [-h] [-o OUTPUT] [-r] [-f] [-t THREADS] [--csv CSV]
                   [-s TABLE] [-R READ_ID_COLUMN] [-c COLUMNS [COLUMNS ...]]
                   [--template TEMPLATE] [-T] [-M] [-D]
                   inputs [inputs ...]

Given one or more pod5 input files, take subsets of reads into one or more pod5 output files by a user-supplied mapping.

positional arguments:
  inputs                Pod5 filepaths to use as inputs

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        Destination directory to write outputs (default:
                        /home/user/ydliu/hitbic/HG002)
  -r, --recursive       Search for input files recursively matching `*.pod5`
                        (default: False)
  -f, --force-overwrite
                        Overwrite destination files (default: False)
  -t THREADS, --threads THREADS
                        Number of subsetting workers (default: 8)

direct mapping:
  --csv CSV             CSV file mapping output filename to read ids (default:
                        None)

table mapping:
  -s TABLE, --summary TABLE, --table TABLE
                        Table filepath (csv or tsv) (default: None)
  -R READ_ID_COLUMN, --read-id-column READ_ID_COLUMN
                        Name of the read_id column in the summary (default:
                        read_id)
  -c COLUMNS [COLUMNS ...], --columns COLUMNS [COLUMNS ...]
                        Names of --summary / --table columns to subset on
                        (default: None)
  --template TEMPLATE   template string to generate output filenames (e.g.
                        "mux-{mux}_barcode-{barcode}.pod5"). default is to
                        concatenate all columns to values as shown in the
                        example. (default: None)
  -T, --ignore-incomplete-template
                        Suppress the exception raised if the --template string
                        does not contain every --columns key (default: None)

content settings:
  -M, --missing-ok      Allow missing read_ids (default: False)
  -D, --duplicate-ok    Allow duplicate read_ids (default: False)

Example: pod5 subset inputs.pod5 --output subset_mux/ --summary summary.tsv --columns mux```

**Comment by HalfPhoton** [comment] 2023-06-28 12:14
Sorry, my error. I meant to say `pod5 convert` not `pod5 subset` when explaining the `--strict` option above.

**Comment by HalfPhoton** [comment] 2023-06-28 16:35
Are you happy with the solution @HITzhongyu , can we close this issue?

**Comment by HITzhongyu** [comment] 2023-06-29 00:48
Hi @HalfPhoton 

sure!
Thank you very much for your patient explanation!

Kind regards,
Zhongyu

**Closed** 2023-06-29 08:02 UTC
